#!/usr/bin/env python3
"""Generate src/unicode_tables.rs — sorted Unicode property ranges (full range,
BMP + astral) for L, N, M, Lu, Ll. Mirrors the C version's classification so the
Rust pre-tokenizer is byte-for-byte parity with tuetoken (and HF/tiktoken).
Run: python tools/gen_unicode_rs.py
"""
import sys
import unicodedata

LETTER = {"Lu", "Ll", "Lt", "Lm", "Lo"}
NUMBER = {"Nd", "Nl", "No"}
MARK = {"Mn", "Mc", "Me"}
# \p{P} (punctuation) + \p{S} (symbol), one combined category for the DeepSeek
# pre-tokenizer's `[\p{P}\p{S}]+` run and `[^\r\n\p{L}\p{P}\p{S}]` prefix.
PUNCTSYM = {"Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So"}


def collect():
    b = {"L": [], "N": [], "M": [], "Lu": [], "Ll": [], "PS": []}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        cat = unicodedata.category(chr(cp))
        if cat in LETTER:
            b["L"].append(cp)
            if cat == "Lu":
                b["Lu"].append(cp)
            elif cat == "Ll":
                b["Ll"].append(cp)
        elif cat in NUMBER:
            b["N"].append(cp)
        elif cat in MARK:
            b["M"].append(cp)
        elif cat in PUNCTSYM:
            b["PS"].append(cp)
    return b


def ranges(cps):
    out = []
    for cp in cps:
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def emit(b):
    L = [
        "// Auto-generated by tools/gen_unicode_rs.py — do not edit.",
        f"// Unicode {unicodedata.unidata_version}.",
        "// Per property: a BMP bitmap (1024 u64 = bits 0..0xFFFF) for O(1) lookup,",
        "// plus sorted (lo,hi) ranges for the astral planes (cp >= 0x10000).",
        "",
    ]
    names = {"L": "LETTER", "N": "NUMBER", "M": "MARK", "Lu": "UPPER", "Ll": "LOWER",
             "PS": "PUNCTSYM"}
    for k, name in names.items():
        cps = b[k]
        # BMP bitmap
        bm = [0] * 1024
        astral = []
        for cp in cps:
            if cp < 0x10000:
                bm[cp >> 6] |= 1 << (cp & 63)
            else:
                astral.append(cp)
        L.append(f"pub static {name}_BMP: [u64; 1024] = [")
        for i in range(0, 1024, 8):
            L.append("    " + ", ".join(f"0x{bm[j]:x}" for j in range(i, i + 8)) + ",")
        L.append("];")
        rs = ranges(astral)
        L.append(f"pub static {name}_ASTRAL: &[(u32, u32)] = &[")
        row = []
        for lo, hi in rs:
            row.append(f"(0x{lo:X},0x{hi:X})")
            if len(row) == 6:
                L.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            L.append("    " + ", ".join(row) + ",")
        L.append("];")
        L.append("")
    return "\n".join(L)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "src/unicode_tables.rs"
    b = collect()
    open(out, "w").write(emit(b))
    print("wrote", out, {k: len(ranges(v)) for k, v in b.items()})


if __name__ == "__main__":
    main()
